services:
  mongo:
    image: mongo:7-jammy
    restart: always

  express:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      - PORT=5000
      - MONGO_URL=mongodb://mongo:27017
    ports:
      - "5000:5000"
    depends_on:
      - mongo
